# Generated by Django 2.0.6 on 2018-07-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(max_length=195, verbose_name='文章摘要'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='avatars/default.gif', upload_to='avatars/'),
        ),
    ]
