# Generated by Django 2.0.6 on 2018-07-16 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180714_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletotag',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='文章题目'),
        ),
        migrations.AlterField(
            model_name='articletotag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Tag', verbose_name='文章标签'),
        ),
    ]
